apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: wisecow
spec:
  secretName: certificate-secret
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer
  commonName: wisecow.com
  dnsNames:
  - wisecow.com