apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
  namespace: wisecow
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mail@rakeshbajpayee.in
    privateKeySecretRef:
      name: private-key-cert
    solvers:
    - http01:
        ingress:
          class: nginx 