apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
    kubernetes.io/ingress.class: nginx
  name: wisecow-ingress
  namespace: wisecow
spec:
  rules:
  - host: wisecow.com
    http:
      paths:
      - backend:
          service:
            name: wisecow
            port:
              number: 4499
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - wisecow.com
    secretName: certificate-secret